# matrices

In [3]:
c


In [9]:
matrix_1=np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [10]:
#shape of the  matrix
matrix_1.shape

(2, 2)

In [14]:
matrix_2=np.array([[10,35,40],[50,64,80],[20,15,90]])
print(matrix_2)
matrix_2.shape

[[10 35 40]
 [50 64 80]
 [20 15 90]]


(3, 3)

### Creating matrices with random values

In [16]:
random_matrix=np.random.rand(3,3)
random_matrix#we get matric random values with less than 1 and they all are floating values

array([[0.76095638, 0.88634188, 0.39016484],
       [0.88893116, 0.81660997, 0.78850087],
       [0.40460303, 0.98934023, 0.38247545]])

In [27]:
#creating matrices with random integers
random_integer_matrix=np.random.randint(60,size=(3,3))
random_integer_matrix

array([[17, 28, 59],
       [36,  1, 39],
       [54,  9, 22]])

#### Matrix with all the values as 1

In [34]:
matrix_3=np.ones((3,3),dtype=int)
matrix_3


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
#matrix with all the values as zeros
matrix_3=np.zeros((3,3),dtype=int)
matrix_3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
#identity matrix
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
#identity matrix
identity_matrix=np.identity(3,dtype=int)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [45]:
#transpose of matrix
a=np.random.randint(50,size=(3,4))
a

array([[16, 14, 38, 49],
       [42, 46, 34, 31],
       [35, 22, 29, 43]])

In [46]:
transpose_of_a=np.transpose(a)
transpose_of_a

array([[16, 42, 35],
       [14, 46, 22],
       [38, 34, 29],
       [49, 31, 43]])